/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaseCard: typeof import('./components/CaseCard.vue')['default']
    DziViewer: typeof import('./components/DziViewer.vue')['default']
    EdgeStatusBadge: typeof import('./components/EdgeStatusBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TileSourceBadge: typeof import('./components/TileSourceBadge.vue')['default']
  }
}
